jaka_zu3:
  gripper_effort_controller:
      type: "effort_controllers/JointTrajectoryController"
      joints: 
        - tool_joint

      gains:
        tool_joint: {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
        